# https://www.mkdocs.org/user-guide/configuration/

site_name: ShortyCut

nav:
  - Home: index.md
  - Introduction:
    - Keywords: keywords.md
    - ShortyCut: shortycut.md
    - Installation: installation.md
  - Defining shortcuts:
      - File format: file-format.md
      - Shortcut syntax: shortcut-syntax.md
      - Multi-link shortcuts: multi-link-shortcuts.md
      - POST links: post-links.md
      - Hotkeys: hotkeys.md
      - Grouping: grouping.md
      - Default search engine: default-search-engine.md
      - Loading separate files: loading-separate-files.md
  - Browser integration:
    - Overview: browser-integration.md
    - Homepage: homepage.md
    - Keyword query: keyword-query.md
    - Web server: web-server.md
  - Miscellaneous:
    - Configuration: configuration.md
    - Favicons: favicons.md
    - API: api.md
    - License: license.md
    - Release notes: release-notes.md

theme:
  name: readthedocs
  collapse_navigation: false
  titles_only: true
  highlightjs: false

docs_dir:  ./

site_dir: ../../src/html/resources/docs

extra_css:
  - css/custom.css

use_directory_urls: false
